### PR TITLE
Variable polling interval for Account

### PR DESCRIPTION
**Pull request by KuroTsuto**
Moves all `chats.json` polling state and control from `ui.js` to the `Account` class, and adds methods to start, stop, and modify the polling interval. Provides some utility groundwork for #16, #24, #46, and possibly #11

### CODE REVIEW

**Comment by hackmud-dtr** [comment]
As with my comment PR 66, I think this is moving things into the wrong direction. chat.js is a UI-agnostic API layer, and polling rate is a UI decision. Wrapping the chat.api classes to make derived versions suitable for this particular UI could work well, but I (personally) think chat.js should stay completely unaware of it's UI so that it can be grabbed for anything.

**Comment by seanmakesgames** [comment]
I had dtr write this up in here as n00bish and him had this same concern. I think it's just a question of moving the code.

**Comment by KuroTsuto** [comment]
Ah interesting. A lot just clicked into place for me regarding the organization of the code - I appreciate the time taken to explain it to me. I'd be happy to port the logic into `ui.js`, but think that a new "controller" layer would be awesome! I've left my thoughts in #66

**Comment by KuroTsuto** [comment]
Closing this PR, as the relevant issue is bottlenecked. Further discussion in #73

**Comment by KuroTsuto** [comment]
Reopening... Is it sensible to move forward by monkey-patching until we can sort out whatever's going to happen with the logic layer?

**Comment by seanmakesgames** [comment]
Probably not a high enough priority of an issue to fix before.

**Comment by KuroTsuto** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
