### PR TITLE
Settings (chat color & ignore list)

### PR DESCRIPTION
**Pull request by ethankaminski**
Adds support for user settings, /-commands (such as `/help`), and two specific settings:

* color_code, set with `/color <char>`: this automatically wraps your chats in color escape sequences. Something that portions of the playerbase built into their own chat scripts (only supports simple formatting, so far).
* ignore_list, add users with `/ignore <user>`: displays messages from these users in a new, de-emphasized style (0.3 alpha).

This does use localStorage, and I haven't tested whether it breaks if that's disabled. I'll see if I can get someone to test that.

Depends on PR #5, since this makes use of the CSS added there.

### CODE REVIEW

**Comment by seanmakesgames** [comment]
I'm confused why, but it looks like commits from the other PR (the stylesheet and the font files) are still showing up in this PR. Usually those disappear from the diff when I merge them from another branch.

**Comment by ethankaminski** [comment]
Huh, so they are. That's weird. Want me to try deleting this and creating a new one, to see if that gets a clean diff?

**Comment by seanmakesgames** [comment]
yeah, I know it's a bit pedantic, but might be good to figure it out for reducing future review sizes. (even if it merges fine)

**Comment by ethankaminski** [comment]
Oh, I totally understand the desire. I've done open source pull request review before - having clean pull requests is *really* helpful.

**Pull request closed without merging**
